# Generated by Django 5.2.17 on 2026-08-29 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('COLLECTED', 'Collected'), ('SORTED', 'Sorted'), ('TRANSFERRED', 'Transferred'), ('PROCESSED', 'Processed'), ('RECOVERED', 'Recovered')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.materialbatch')),
            ],
        ),
    ]
