# Generated by Django 5.2.17 on 2026-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organisation_type', models.CharField(choices=[('COUNTY', 'County Government'), ('COLLECTOR', 'Collector'), ('PROCESSOR', 'Processor'), ('GENERATOR', 'Generator'), ('CBO', 'Community-Based Organisation'), ('OTHER', 'Other')], max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
